version: '3.3'

services:

  web:
    image: ${DOCKER_REPO}/gutenberg-http:${BUILD_TAG}
    build: .
    ports:
      - ${APP_PORT}:80
    restart: "${APP_RESTART}"
    environment:
      - GUTENBERG_DATA=/data/${APP_DB}
      - APPINSIGHTS_INSTRUMENTATIONKEY=${APPINSIGHTS_INSTRUMENTATIONKEY}
    volumes:
      - ./:/data
