from os import getenv

METADATA_CACHE_SIZE = int(getenv('GUTENBERG_HTTP_METADATA_CACHE_SIZE', '256'))
BODY_CACHE_SIZE = int(getenv('GUTENBERG_HTTP_BODY_CACHE_SIZE', '16'))
SEARCH_CACHE_SIZE = int(getenv('GUTENBERG_HTTP_SEARCH_CACHE_SIZE', '32'))
